# Generated by Django 4.2.25 on 2025-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('category', models.CharField(choices=[('experience', 'Work Experience'), ('skills', 'Technical Skills'), ('education', 'Education'), ('projects', 'Projects'), ('preferences', 'Work Preferences'), ('achievements', 'Achievements'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Data',
                'ordering': ['category', '-created_at'],
            },
        ),
    ]
